version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: simulador_db
    restart: always
    environment:
      MYSQL_DATABASE: simulador_tactico
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: entrenador_user
      MYSQL_PASSWORD: entrenador_password
    ports:
      - "3313:3306"
    networks:
      - simulador-net

networks:
  simulador-net:
    driver: bridge