spring.application.name=simuladorTactico
server.port=8080

# Conexion a BD
spring.datasource.url=jdbc:mysql://localhost:3313/simulador_tactico?createDatabaseIfNotExist=true
spring.datasource.username=entrenador_user
spring.datasource.password=entrenador_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# JWT Config
jwt.secret=clave_secreta_simulador_2026_pro
jwt.access.expires=3600000
jwt.refresh.expires=604800000
jwt.issuer=simulador-tactico